# Generated by Django 5.1 on 2024-08-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
