# Generated by Django 5.1 on 2024-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_consumer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
