# Generated by Django 5.1 on 2024-08-21 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_alter_consumer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='dining.consumer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expences', to='dining.products')),
            ],
        ),
    ]
