# Generated by Django 5.1 on 2024-08-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0005_rename_expences_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_count', models.IntegerField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='dining.consumer')),
            ],
        ),
    ]
